pkzip -a -ex ezdsl303.zip dtstbool.dpr
pkzip -a -ex ezdsl303.zip dtstbtre.dpr
pkzip -a -ex ezdsl303.zip dtstcoll.dpr
pkzip -a -ex ezdsl303.zip dtstgen.pas
pkzip -a -ex ezdsl303.zip dtsthash.dpr
pkzip -a -ex ezdsl303.zip dtstlist.dpr
pkzip -a -ex ezdsl303.zip dtstsortlist.dpr
pkzip -a -ex ezdsl303.zip dtststak.dpr
pkzip -a -ex ezdsl303.zip exinsdup.dpr
pkzip -a -ex ezdsl303.zip exintque.dpr
pkzip -a -ex ezdsl303.zip exlngstk.dpr
pkzip -a -ex ezdsl303.zip exstrstk.dpr
pkzip -a -ex ezdsl303.zip EZBitCnt.INC
pkzip -a -ex ezdsl303.zip ezdsl.doc
pkzip -a -ex ezdsl303.zip EZDSL3d3.DPK
pkzip -a -ex ezdsl303.zip EZDSL3d3.RES
pkzip -a -ex ezdsl303.zip EZDSL3d4.DPK
pkzip -a -ex ezdsl303.zip EZDSL3d4.RES
pkzip -a -ex ezdsl303.zip EZDSL3d5.DPK
pkzip -a -ex ezdsl303.zip EZDSL3d5.RES
pkzip -a -ex ezdsl303.zip EZDSL3d6.DPK
pkzip -a -ex ezdsl303.zip EZDSL3d6.RES
pkzip -a -ex ezdsl303.zip EZDSLBAr.PAS
pkzip -a -ex ezdsl303.zip EZDSLBse.PAS
pkzip -a -ex ezdsl303.zip EZDSLBtr.PAS
pkzip -a -ex ezdsl303.zip EZDSLCol.PAS
pkzip -a -ex ezdsl303.zip EZDSLCts.PAS
pkzip -a -ex ezdsl303.zip EZDSLCts.R16
pkzip -a -ex ezdsl303.zip EZDSLCts.R32
pkzip -a -ex ezdsl303.zip EZDSLCts.RC
pkzip -a -ex ezdsl303.zip EZDSLDbl.PAS
pkzip -a -ex ezdsl303.zip EZDSLDef.INC
pkzip -a -ex ezdsl303.zip EZDSLHsh.PAS
pkzip -a -ex ezdsl303.zip EZDSLLst.PAS
pkzip -a -ex ezdsl303.zip EZDSLOpt.INC
pkzip -a -ex ezdsl303.zip EZDSLPQu.PAS
pkzip -a -ex ezdsl303.zip EZDSLQue.PAS
pkzip -a -ex ezdsl303.zip EZDSLRnd.PAS
pkzip -a -ex ezdsl303.zip EZDSLSkp.PAS
pkzip -a -ex ezdsl303.zip EZDSLStk.PAS
pkzip -a -ex ezdsl303.zip EZDSLSup.PAS
pkzip -a -ex ezdsl303.zip EZDSLThd.PAS
pkzip -a -ex ezdsl303.zip EzIntQue.pas
pkzip -a -ex ezdsl303.zip EzLngStk.pas
pkzip -a -ex ezdsl303.zip EZPrimes.INC
pkzip -a -ex ezdsl303.zip EzStrStk.pas
